/**********************************************************
 * BEWARE: This file is a autogenerated stub!
 *********************************************************/

#include <stdlib.h>

#include "include/capi/cef_task_capi.h"

#include "cef/base.h"
#include "util.h"
#include "initializers.h"

CEF_CALLBACK void task_execute_task1(struct _cef_task_t *self)
{
	DEBUG_PRINT("running task1")
}
CEF_CALLBACK void task_execute_task2(struct _cef_task_t *self)
{
	DEBUG_PRINT("running task2")
}
struct _cef_task_t *init_task(smurf_task task)
{
	struct _cef_task_t *ret = NULL;
	struct refcount *r = NULL;
	char *cp = NULL;

	DEBUG_ONCE("called");
	if (!(r = calloc(sizeof(struct refcount) + sizeof(struct _cef_task_t), 1))) {
		DEBUG_PRINT("#### out of memory! #####");
		return NULL;
	}

	cp = (char*)r;
	cp += sizeof(struct refcount);
	ret = (struct _cef_task_t*)cp;

	if(!init_base((cef_base_t*)ret, sizeof(struct _cef_task_t))) {
		free(r);
		return NULL;
	}
	ret->base.add_ref((cef_base_t*)ret);

	// callbacks
	switch(task) {
	case SMURF_TASK_1:
		ret->execute = &task_execute_task1;
		break;
	case SMURF_TASK_2:
		ret->execute = &task_execute_task2;
		break;
	}

	return ret;
}